# Generated by Django 4.2.1 on 2023-06-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=11)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
