# Generated by Django 4.2.1 on 2023-06-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='age',
            field=models.IntegerField(),
        ),
    ]
